spring.application.name=Menu_Service
server.port=8082

#DATABASE CONNECTIVITY

# look for port 1521, for the instance named "XE"
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE

# credentials 
spring.datasource.username=system
spring.datasource.password=root

# acts as a translator between Java and Oracle SQL
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Object-Relational Mapping
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

#Syncs Java/DB
spring.jpa.hibernate.ddl-auto=update

#Shows SQL in console.
spring.jpa.show-sql=true

#CIRCUIT BREAKER 

#Looks at the last 10 calls to decide if the service is healthy.
resilience4j.circuitbreaker.instances.restaurantService.slidingWindowSize=10

#Circuit breaker will only start working after at least 5 calls.
resilience4j.circuitbreaker.instances.restaurantService.minimumNumberOfCalls=5

#If 50% of the calls fail, the circuit breaker will OPEN i.e.(Stop calling Restaurant Service).
resilience4j.circuitbreaker.instances.restaurantService.failureRateThreshold=50

#Once OPEN, wait 10 seconds before trying again.
resilience4j.circuitbreaker.instances.restaurantService.waitDurationInOpenState=10s

# After 10 seconds, allow 3 test calls.If they succeed,circuit closes (normal flow resumes).If they fail, circuit opens again.
resilience4j.circuitbreaker.instances.restaurantService.permittedNumberOfCallsInHalfOpenState=3