spring.application.name=Restaurant_Service
server.port=8081


# look for port 1521, for the instance named "XE"
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE

# credentials 
spring.datasource.username=system
spring.datasource.password=root

# acts as a translator between Java and Oracle SQL
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Object-Relational Mapping
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

#Syncs Java/DB
spring.jpa.hibernate.ddl-auto=update

#Shows SQL in console.
spring.jpa.show-sql=true